# 设置端口号为6666
server:
  port: 6666
# 配置log文件
logging:
  level:
    root: info
  file:
    path: ./logs
test:
  version: 1.0
# 是否需要校验
loginValidator:
  #  如果启动需要登录注解，则默认所有的接口都不需要登录校验。
  enableNeedLoginAnnotation: true
  #  如果启动无需登录注解，则默认所有的接口都需要登录校验。
  enableNoNeedLoginAnnotation: false